name: music_sync_app
description: MusicSync 手机端 - 本地音乐特征扫描与差异比较
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  path: ^1.9.0
  xxh3: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "./assets/1.jpg"
  android: true
  ios: false
